import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ClientNav from "@/components/ClientNav";
import { Toaster } from "@/components/ui/toaster";
import AppProvider from "@/Context/Context";
import LoadingComponent from "@/components/LoadingComponent";
import { GoogleOAuthProvider } from '@react-oauth/google';
import React, { Suspense } from "react";
import Loading from "./loading";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import QueryProvider from "@/Context/QueryProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Freet.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
     <React.StrictMode>
      <html lang="en" suppressHydrationWarning>
      <body>
        <Suspense fallback={<Loading/>}><></></Suspense>
        <GoogleOAuthProvider clientId="251347409729-4ebihjc5jjhof6fqchid3u310msmrfr1.apps.googleusercontent.com">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <QueryProvider>
              <AppProvider>
                  <ClientNav>
                      {children}
                  </ClientNav>
              <Toaster/>
           </AppProvider>
            </QueryProvider>
        </ThemeProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
     </React.StrictMode>
    
  );
}
